dist: xenial
language: python
python:
- '3.7'
- 3.7-dev
- 3.8-dev
- nightly
install:
- pip install -r requirements.txt
- pip install flake8
- python setup.py install
script:
- flake8 bni_api
- python test.py
env:
  global:
  - secure: Y2vLBFUQMVslbjeNKOBhx0DV945DmFBto3jAFhWnhKyMlClPJzunrZjRP1P+N32AtK6qq9IUHCEayolaHAP1bCPNrR/n8gJOOuUyFqIXOvV6QKZ1LpgDZaB01hXereOjgH9om9gsv+YJ+XxRT9hUM7BloAelJMGpOVjcZ4MCyMCXPJFTvGJ83cLFr0/A31OLuQ6gqAhFZGfm91d7RTH5zkl5Ns3Itq2KpN+m59mwTFqZsomN9viHXtw051dyViCcaOGbgyWHSQ64L9YA5FPaCogjL2T5/ql1vS3RlFQpmR7plClDbwzaKST1CSAzyk14U8QrtP21nrO8dZAbYgpw88lG9DJ5FtSDVZoIvVbK3dshuVtlOxLWjaSrbtH+3g6CS++QJ8i9Qi0c11PUD1eizg14FC4H7sM3HNJYLezJ2xXrME4NTxgNfgTAjMXfNVT6i+ci89bZWbfv+Uw3XCo6USZDFHmxAfmBoadQV0CztQA7ns63ZULh1OsX7vZAeGSJEaW0yz4ttx5X5I5xcJYFaGmDNOfj0XMm2F6d9DCL0/iynguucXJygF704wCzpMTU+hD93+NP7zs5m4wHsrW/1Nd2wTVfytAkMbAMjYnRX4W7z43YspBakL0RJXUlQkCcTbAd93KrNlhlcbXBPq29eB7eV52GUQdUV399cxLkJoQ=
  - secure: s/7tt7IweQRaKJPR/iXKtmDHprcZiry/aO+EtNY6BgOs1XC5YC/S0Mn+JjGYc0miYKa4kcns7MyLiPhYluLpZ+Yh7Ab83W8X2zjpLAi1dGApIGyTKQuZL/YM2ZRfLTEBEQDvu+ffBzmhEhvRaq00Dq8UXdhgr2oolPWm6it3PNQZlcwOp4I+3XukH2vr4ltwVjkjBlhloMgelKuxzEFv4utBfQYoJn59RMR1mXGkHrhVwvU24mznd10nKoWV8IHL+98cZQ0WbJBsE9ZELAM4tg729lWS1TrKryXqQxhy2h7Dnh30U1y15u2mioPH3h2bUudrgNPxH4T95uYH9lPSZTFk3qcGXMZRV82XoaHk9HC+15BtsfoKedu0dMBue1vs7hq86kD7ynRL0XMZcn0MWxM8UmNTh6gaYGC2l30ZvUejN0rQHTkG4sJ1YIqbP+u6C+lYfLmxMzqCoa2AuZGOA/pLW5Q9rjZ8yE+6hh7RGvG9Y3q7qgEhjaw7wfvYo/7fqM9InaY0BhYeieYaN/2Ol07pSP/mt2pae/UxyL5NUVbltpwpHUkCo0qwXczOO+ABR7/OfZs0WHrRl8DcKxhXGxkh9xbAQwT05rOHt5Pxi2ILWzdKdWPh6e7BVVMaci3o9XU9HehkRoLR1w/Y72bqy8V2eDMhbfSuzV9AG6uoqEk=
