dist: xenial
language: python
python:
- '3.7'
- 3.7-dev
- 3.8-dev
- nightly
install:
- pip install -r requirements.txt
- pip install flake8
- python setup.py install
script:
- flake8 bni_api
- python test.py
env:
  global:
  - secure: vPHrAuRBSrNPR8jzjyMjXccCy8+ZyGtRT+wwzWIEBMJYo2JIOw/DE/URkeAC4AavJ8RlM3fDavdUXxYmw1/Y8ZNPpxxZbRkikjrVEGVv8darMGHQMB3aMt7Sjso+/I2WVced0XVXXP0Yfrp+eFo0YWcqUAFGyMtwuchendTtJNUFmtpVE7Cae8D92C9HPeqon2TJGhyddlzvZAvOKGiVgf4kgmFZiIXlIhJwZq9qBhAE0md2j71RZKShgl08IDYBdEh0AoawRYfgP73TN1qv7Pn64sZJQXsTMXm3fkJKO8MO88V3rY3aUbJEWWY4SLvyN5kwUPwdet0DDbes+9A3w/bQ64lvbtBz/goQ6ylLFm7t3ZFRKqIxjgToL2EN3DB0voRhq6CPoEb8e1qpcj2FaQjSHrl3Z+2o3zj4ynAHvNLrR81PVQXcjbOBXLRC4uIy2LU+q1B8HnXU7hWLsVM9xi7iHzsSxS23by+wkQG5dsyJg35a1ft7EY8H70OmC+PoovVPGyjvyGc3H5sME73nTsMw8f3y4ArsFT1keG2PS5lkrNO7DMLlXPi1S2vTVYDq6SVdOMoi4H1ylQYyqb2TbDr14d/BR3wWVyA8eamARh+KSaSDhItCK5EHsrrHmRczaGgcUd8Zd++LzYY6MfpXOf0yma5m7O+v3ZnlGI/iauA=
  - secure: MbWntuIBS4NkIPIcZNDWV0JMEDBhZY8R5KUe2dw8m1lf8+V3NFwnZ0X7h1eFbASGkanpq+7Jt1yMCy6WsnW3Bh8ej/L6P/VFyo+INztPJB+8G6ANKAGrMyKoXGqDR0VwajHRSRIy7OUTD52Q1uz4jpk8O3brQ3WA1+IbpmtFBF4m3PnfY+VfGGeMFabseK46lNX85fEu17mF0JTPxPzL0+jsTEX8/ELdH4xOrxRvVgmcSuZodL8nk0Zm320x7JdixLDC8HflsX7VrKT3uMGWA6TWvyymMA8ZevNNFP1S2csjEbp1YJbaMG+aKyUeQXx+XHln31HxAnEpXHZTmA9LGX6YLa7oDPxLx86K5vL9v0MQ/QQ2v+K3QCvqrnWAZ5vDLT/zkUhl2GMAwHHcp1lLOY98X+tXtv/0R653hOKYwq9NKrDCKwcdvY8/k6fbg4THUzLJBmgQgBRkg5whGgaCnYvbP8l7pD+v7HcvdVv6xsfLWkWRTUnbZHHfPd1hMKJ2bHW01vrGajw9x2Gpwqleh1YON9NDqHYMAqoMHE2gr2qeagPZyzDSiF2QLGXYbEUmolBux6TfN//3+0yMfclVenE2+wBcvJEn1t3OdTIBrFPE04REtWcqU89Pv1c+KXC6tXZvzZ/QXd3/78OWxuwP1Qme+lSvLOy5Nm4ui2VOOYg=
