dist: xenial
language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
- pip install flake8
- python setup.py install
script:
- flake8 bni_api
- python test.py
env:
  global:
  - secure: xMOGbT8VwdFOIIjSfDRzeK2NrCm06Wq0HCN+hvxWe+8syu+PHA8aJKKIQozNYJrx9GDuzYhIyk3+fVQIHKFKLI5iZV5xP0RSlcgiLFyp/tIda+LCEESqF1/FeKI/SvLDuLGeEgWvZn+9jzSs4sg+T1YL+X3QUWDRh23i69zkbYI8YleMbPMkFiw0EwF41EUb60WQpz7tem8A8fQg50UcoBbylrvyB0w7gbu5lw93kQ8Pp7zNoiWXXxSfrKEy1cSbki1c02/F1tzRqd/Z0M0vLNAoZ15aMFICQTgKLiD5Ssc6uoQBHHYc3i2Iz6d3YA6D3+JDF7eg82Nn/wMEdwlCWZXByuRRxZJgAC5+NoOTzwJEXV8WmVuPIaKfi+LFXNrSudYeBpd1DOxBWkMyOMupFAT49V75VDkIdAMKGpFHYS7PJ1ZmJgO6kFxxzdlujJhC/0ut8rlB9UXSI/DQk9S+KBvXMsn9BVvit8ngNh46i7gEI1CD0lnYYyE4qoEiN0uSpTseGvU3hYTFVPN/TL2qV8vYgtEobAVRNIpGbQX2+WWL2K3KDahAd5C3gwuPKlZKhbgX+S0PVnSyaBslLpciViDD2/wpGTdcDXOd6lAdF6Iqjt4iOJVjfMHzHPDmBe3gc13UOKD6F1jlqNs54Yeq5GzbDzrCkZsrSXwZkzCFGhk=
  - secure: kgMqP1AwP7CNR4BsFlypOU52Z+a1hhxsinxrwbn+WdRxTajWMl9ynI+TT9hKHz9b7n9jHD13mromFyjqmF+/+lssVzHgOSFZESimt9CYBpuh1CZsh5dWUjxNBS5AmMj9MldVI/Oq+MHCundSNHl9n63Sq5w34VFlMqyaJrV+QjY+y+p+N/bXlbl+IaLazlJpuq7kLSW9D0d+gxhGbjmAhmNPy4KHD6PELtt1rIMIhPdTimlHWC2RIVsaDPq6UF10Up3YDj/TjKLFGLcJlqFAezf/1h/aM46m+N9Wz7ngiiwpVhXI38lWN43lYlqGakJl9zUN+pNUfsMBDXxC12DslEdS0+ElpV5c9UPl4/6W8d9GceBgGTMsCoIYv1Ma6OKVARPyXHgTZ1Z4kMsbba/EttOjYsC2Vu6wMg9XQkSdQWvoYUnnMoyMMUxiuPSJDKKCPcgCyhKSyYdH77MdBls54gzSqNbDVsuOfmlVrkxp8uGRO7Eb1NSKhJ01kmoI39q+Tm2ymma32Yrgnv+B/4hs9+cI8q2nzALWRFijbMBg5ecXWCw9Ap2ZPTpkkqFvCicmBzVQr0HfXE3axypyP6j4kmDmc5M27ivBrPseGO7op1uAShSV8IcnV16wRBt9cYTKvuZpCQANmyETRmR6fnKU7MZ7zSZITqXzkd/PMr+LhGM=
